/* SPDX-FileCopyrightText: 2026 The Oxys-OS Authors */
/* SPDX-License-Identifier: LGPL-3.0-or-later */
/*
 * File: kernel/include/oxys/gfx/face.h
 * Purpose: The desktop's face: Inter, drawn smoothly on a grid of five by
 *          eight units of the scale, or proportionally by its own advances.
 * Key functions: FaceCoverage, FaceDrawGlyph, FaceTextWidth, FaceDrawText, FaceInkText.
 * References:
 *   - docs/design/CONSOLE.md: the two faces, and why the boot log and the
 *     fault screen keep the 8-by-8 one.
 *   - fonts/inter/face.h: the coverage tables, generated by tools/face.sh.
 */

#ifndef OXYS_GFX_FACE_H
#define OXYS_GFX_FACE_H

#include <oxys/types.h>
#include <oxys/gfx/graphics.h>

/* A cell, in units of the scale: SYSCALL_WINDOW_TEXT_ADVANCE by _HEIGHT. */
#define FACE_WIDTH  5
#define FACE_HEIGHT 8

/* The largest scale drawn from a table of its own; larger ones are sampled. */
#define FACE_TABLE_SCALE_MAXIMUM 4

/*
 * How much of the pixel at a column and row of the cell the glyph covers, 0 to
 * 255, at a scale of 1 to 8. Zero for a coordinate outside the cell, a scale
 * out of range, or a code the face does not cover.
 */
uint8_t FaceCoverage(uint8_t code, int32_t scale, int32_t column, int32_t row);

/*
 * Draws a glyph in the cell of FACE_WIDTH by FACE_HEIGHT times the scale at
 * (x, y): the paper over the whole cell, then the ink blended over it at each
 * pixel's coverage. Both colours are pixels as the surface stores them. A code
 * outside 0x20 to 0x7E draws a hollow box, so an unmapped character is visible.
 */
void FaceDrawGlyph(GraphicsSurface *surface, int32_t x, int32_t y, uint8_t code, uint32_t ink,
                   uint32_t paper, int32_t scale);

/*
 * The width in pixels of a run of text at a scale: on the grid, FACE_WIDTH
 * times the scale a character; proportionally, the sum of Inter's own
 * advances, rounded up. Zero for a scale out of range or a null text.
 */
int32_t FaceTextWidth(const char *text, int32_t scale, bool proportional);

/*
 * Draws a run of text with its top-left at (x, y) and returns its width, as
 * FaceTextWidth gives it. On the grid each character fills its cell; in
 * proportional text the paper covers the run's width and the full height, and
 * each glyph's ink is blended where the font's advances put it, so neighbours
 * whose ink overhangs do not erase one another.
 */
int32_t FaceDrawText(GraphicsSurface *surface, int32_t x, int32_t y, const char *text,
                     uint32_t ink, uint32_t paper, int32_t scale, bool proportional);

/*
 * The ink of a proportional run alone, blended over whatever the surface holds,
 * with no paper: text standing on a picture, as the desktop's names do. Returns
 * the run's width.
 */
int32_t FaceInkText(GraphicsSurface *surface, int32_t x, int32_t y, const char *text,
                    uint32_t ink, int32_t scale);

#endif /* OXYS_GFX_FACE_H */
