/* SPDX-FileCopyrightText: 2026 The Oxys-OS Authors */
/* SPDX-License-Identifier: LGPL-3.0-or-later */
/*
 * File: kernel/include/oxys/gfx/face.h
 * Purpose: The desktop's face: Inter, drawn smoothly into monospaced cells of
 *          five by eight units of the scale.
 * Key functions: FaceCoverage, FaceDrawGlyph.
 * References:
 *   - docs/design/CONSOLE.md: the two faces, and why the boot log and the
 *     fault screen keep the 8-by-8 one.
 *   - fonts/inter/face.h: the coverage tables, generated by tools/face.sh.
 */

#ifndef OXYS_GFX_FACE_H
#define OXYS_GFX_FACE_H

#include <oxys/types.h>
#include <oxys/gfx/graphics.h>

/* A cell, in units of the scale: SYSCALL_WINDOW_TEXT_ADVANCE by _HEIGHT. */
#define FACE_WIDTH  5
#define FACE_HEIGHT 8

/* The largest scale drawn from a table of its own; larger ones are sampled. */
#define FACE_TABLE_SCALE_MAXIMUM 4

/*
 * How much of the pixel at a column and row of the cell the glyph covers, 0 to
 * 255, at a scale of 1 to 8. Zero for a coordinate outside the cell, a scale
 * out of range, or a code the face does not cover.
 */
uint8_t FaceCoverage(uint8_t code, int32_t scale, int32_t column, int32_t row);

/*
 * Draws a glyph in the cell of FACE_WIDTH by FACE_HEIGHT times the scale at
 * (x, y): the paper over the whole cell, then the ink blended over it at each
 * pixel's coverage. Both colours are pixels as the surface stores them. A code
 * outside 0x20 to 0x7E draws a hollow box, so an unmapped character is visible.
 */
void FaceDrawGlyph(GraphicsSurface *surface, int32_t x, int32_t y, uint8_t code, uint32_t ink,
                   uint32_t paper, int32_t scale);

#endif /* OXYS_GFX_FACE_H */
